# Generated by Django 2.1.3 on 2019-12-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0010_auto_20191211_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
