# Generated by Django 2.1.3 on 2020-01-17 17:49

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_add_is_customer_field_for_auth_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=400)),
                ('surname', models.CharField(blank=True, max_length=400)),
                ('name', models.CharField(blank=True, max_length=400)),
                ('phone', models.CharField(blank=True, max_length=400)),
                ('phone_verified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(blank=True, max_length=400)),
                ('state', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=400)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('postal_code', models.CharField(blank=True, max_length=400)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(default=1)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Phone Verified'), (2, 'Personal Info Passed'), (3, 'Store Info Passed')], default=0)),
                ('is_customer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_client',
            },
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SwivelToken',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_token', to='authentication.Client', verbose_name='Client')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='Vendor')),
            ],
            options={
                'verbose_name_plural': 'SwivelToken',
            },
        ),
    ]
