# Generated by Django 2.1.3 on 2020-01-18 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20200117_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=400)),
                ('state', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=400)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('postal_code', models.CharField(blank=True, max_length=400)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Client')),
            ],
            options={
                'db_table': 'prefer_location',
            },
        ),
    ]
